[client]
showErrorDetails = false
toolbarMode = "minimal"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[logger]
level = "error"
message.activationTime = "never"
